name: "Build"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: "Software Install - Ubuntu"
      run: |
        sudo apt-get install -y \
          build-essential \
          coreutils \
          gkrellm \
          libgtk2.0-dev \
          pkg-config \
          software-properties-common \
          wget
    - name: "Software Install - CUDA"
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        sudo apt-get update
        sudo apt-get install -y \
          cuda-nvml-dev-12-6 \
          libnvidia-compute-560
    - name: "Build and Test"
      run: |
        make
        make test
