name: "Build"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Software Install - Ubuntu"
      run: |
        sudo apt-get install -y \
          build-essential \
          coreutils \
          gkrellm \
          libgtk2.0-dev \
          pkg-config \
          software-properties-common
    - name: "Build"
      run: make
